[package]
name = "rustpython-pylib"
version = "0.1.0"
authors = ["RustPython Team"]
edition = "2018"

[dependencies]
rustpython-derive = { version = "0.1.2", path = "../../derive" }
rustpython-bytecode = { version = "0.1.2", path = "../../bytecode" }
maplit = "1.0"
