[package]
name = "rustpython-common"
version = "0.0.0"
authors = ["RustPython Team"]
edition = "2018"

[dependencies]
parking_lot = "0.11.0"
num-traits = "0.2"
num-bigint = "0.3"
lexical = "4"
hexf-parse = "0.1.0"

[dev-dependencies]
rand = "0.7.3"
